const brawlers = [
	{
		name: 'Barley',
		rank: 2,
		trophies: 18,
		power: 2,
		rarity: 'startingBrawler',
		coinsForUpgrade: 20,
		brawlCoins: 200,
		image: '/images/Barley.png',
	},
	{
		name: 'Bo',
		rank: 1,
		trophies: 6,
		power: 1,
		rarity: 'mythic',
		coinsForUpgrade: 10,
		brawlCoins: 100,
		image: '/images/Bo.png',
	},
	{
		name: 'Brock',
		rank: 5,
		trophies: 43,
		power: 5,
		rarity: 'rare',
		brawlCoins: 500,
		coinsForUpgrade: 50,
		image: '/images/Brock.png',
	},
	{
		name: 'Colt',
		rank: 3,
		trophies: 25,
		power: 3,
		rarity: 'superRare',
		coinsForUpgrade: 30,
		brawlCoins: 300,
		image: '/images/Colt.png',
	},
	{
		name: 'El Primo',
		rank: 7,
		trophies: 77,
		power: 8,
		rarity: 'legendary',
		brawlCoins: 800,
		coinsForUpgrade: 80,
		image: '/images/El primo.png',
	},
	{
		name: 'Poco',
		rank: 20,
		trophies: 480,
		power: 20,
		rarity: 'chromatic',
		brawlCoins: 1000,
		coinsForUpgrade: 800,
		image: '/images/Poco.jpeg',
	},
	{
		name: 'Tara',
		rank: 20,
		trophies: 520,
		power: 25,
		rarity: 'chromatic',
		brawlCoins: 1000,
		coinsForUpgrade: 800,
		image: '/images/Tara.png',
	},
];

export default brawlers;
